# Site settings
title: L'Escapade
email: lescapade@domain.com
url: https://ckaenzig.github.io
baseurl: /escapade
description: "L'escapade, un lieu d'accompagnement et d'activité pour séniors, le plaisir d’une journée conviviale, les besoins de la personne âgée sont au cœur de nos préoccupations."


# Color settings (hex-codes without the leading hash-tag)
color:
  background: '#fefdfa'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Build settings
markdown: kramdown
permalink: pretty
