# Site settings
title: Le Jour Bleu
email: jourbleu@domain.com
url: https://ckaenzig.github.io
baseurl: /escapade
description: "Le Jour Bleu, un lieu d'accompagnement et d'activité pour séniors, le plaisir d’une journée conviviale, les besoins de la personne âgée sont au cœur de nos préoccupations."


# Color settings (hex-codes without the leading hash-tag)
color:
  text: '#4a4640'
  text_rgb: '74,70,64'
  white: '#fefcfa'
  white_rgb: '254,252,250'
  links: '#219ab3'

# Footer settings
footer: Le Jour Bleu

# Build settings
markdown: kramdown
permalink: pretty
